version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/RevaRoceries-0.2.war ROOT.war
artifacts:
  files:
    - ROOT.war